### ISSUE TITLE
[BUG] OpenAI result don't generate code

### ISSUE THREAD

**Issue by agustinm20** [zinedkaloc/aipage.dev#30]
# Bug Report

**Description**
I download the last release and set my OpenAI key, when I run the site and execute my prompt, the result is: "Sorry, but I'm unable to generate the HTML code for your requested design as it goes beyond my capabilities as a language model AI."

**Steps to Reproduce**
On every request to OpenAI

**Comment by zinedkaloc** [comment]
It seems the issue might be related to OpenAI. To help narrow it down, could you please try using the example prompts provided in our [README.md](https://github.com/zinedkaloc/aipage.dev/blob/master/README.md#test-prompts)? This will help us determine if the problem is specific to certain prompts or a more general issue.

Thanks for your patience and understanding.

**Comment by agustinm20** [comment]
You're rigth, only happen when the prompt is like "A landing page for Medical website", I mean, basic.

Thanks, this app has potential!

**Comment by agustinm20** [comment]
Works with the examples prompts provided in the [README.md](https://github.com/zinedkaloc/aipage.dev/blob/master/README.md#test-prompts)
